import Head from 'next/head'
import styled from 'styled-components'
import { useAuth } from 'context/auth'
import MatchSwiper from 'components/MatchSwiper'
import MatchSpinner from 'components/Spinner/Match'
import withAuth from 'utils/withAuth'
import { fetchDocuments } from 'utils/helpers'
import { MATCH_CARDS_REF } from 'firebase-config'

export async function getServerSideProps() {
	const cards = await fetchDocuments(MATCH_CARDS_REF)

	return { props: { cards } }
}

function Home({ cards }) {
	const { user } = useAuth()

	const filteredCards = cards.filter((card) => {
		const ignoredCardIds = card.passed.concat(card.liked)
		return card.id !== user.id && !ignoredCardIds.includes(user.id)
	})

	return (
		<Container>
			<Head>
				<title>Tinder clone</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Content>
				<MatchSpinner photoUrl={user.photoUrl} />
			</Content>
			<MatchSwiper cards={filteredCards} />
		</Container>
	)
}

export default withAuth(Home)

const Container = styled.div`
	height: 100%;
	position: relative;
`
const Content = styled.div`
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
`
